### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#10]
I get the following error when launching the app on my Android phone:

TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.billing::Launcher()
	at com.myflashlab.air.extensions.billing.android::Android()
	at com.myflashlab.air.extensions.billing::Billing()
	at com.myflashlab.air.extensions.billing::Billing$/init()
at controllers::Payments$/init()[C:\...controllers\Payments.as:21]

Here's the code:

Billing.IS_DEBUG_MODE = true;
			
>17			Billing.init( 
>18				googleKey,
>19				[ "Peecoins" ],					// Android product ID
>20				[ "Peecoins" ],					// iOS product IDs
>21				onBillingResult );				// callback

Also, are there any tutorials on how to use this ANE with screenshots of where to get the data from Google and Apple? Trying to figure out "which" ID and keys and codes to use is all a bunch of guesswork.

Thanks.

**Comment by myflashlab** [comment]
This is the most common error message which devs will see when they first initialize ANEs. these videos will show you exactly what the problem is: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

highlights are 1) do NOT run on the simulator. 2) make sure the ANE is correctly embedded in to your project/air manifest xml file.
