### ISSUE TITLE
Cant't purchase 

### ISSUE THREAD

**Issue by DFABRIK** [myflashlab/inAppPayments-ANE#20]
As it's written above I always get the same message
![img_2125](https://cloud.githubusercontent.com/assets/18464109/18530328/5a908952-7ad1-11e6-8dac-d8e01c6b604b.JPG)
onInitResult  I get correctly number of items with id. But When I try to purchase with

Billing.doPayment(BillingType.CONSUMABLE, myItemID, "Payload CONSUMABLE", onPurchaseResult);
result is in image.

If I use "android.test.purchased"
I get fake purchase window
![img_2124](https://cloud.githubusercontent.com/assets/18464109/18530385/a0e48d4a-7ad1-11e6-8295-6a36228576ef.JPG)
 I try it with application in alpha state with tester account and in application in publish state with developer account and random account.
Any advice?

**Comment by DFABRIK** [comment]
any comments?

**Comment by Adrian-S** [comment]
Had the same issue, at some point. It's mostly because the product sold has not been propagated trough the servers. Usually you have to wait 1-2 hours, and at some point it will work. I see you posted your first request 2 days ago, so this might not be your case.

Start your checklist again.
Make sure: Billing.IS_DEBUG_MODE = true;
Check Air .xml manifest settings.
Make sure the ID of the app is the same with the one you uploaded as alpha test.
Check Android Public KEY.

I think they do say if the item is not found, check with a random ID. If they say the same error it's most likely from app ID or public key. And don't forget, it takes time to propagate products.

**Comment by gonzos978** [comment]
When we set application to publish  status and remove alpha and beta, looks like everything works fine now.

**Comment by DFABRIK** [comment]
When we set application to publish status and remove alpha and beta, looks like everything works fine now. Tnx.
