### ISSUE TITLE
doBilling not working

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#45]
Testing on Android and not able to get a doBilling to work. I have a logged comment from the line of code prior to doBilling, and then another logged comment on the line of code after, but the comment after doBilling is never reached. There is no logic between them, so something is causing code execution to halt.

Ideas?

**Comment by polyGeek** [comment]
Is there someone I can pay to get support on a phone to get this fixed ASAP?

**Comment by myflashlab** [comment]
For live support, please request that through http://www.myflashlabs.com/contact/
However, could you tell us what does ```$status``` returns on the following?

```actionscript
// initialize the extension by passing in the product IDs and finally a callback function so you will know when the initialization process finishes.
Billing.init("Android KEY from Google Play Console", [Array of Android products], [Array of iOS products], onInitResult);

private function onInitResult($status:int, $msg:String):void
{

}
```
refer to this information: https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L190

**Comment by polyGeek** [comment]
The onInitResult fn returns:

onInit:  status  =  1  :  msg  =  onInitSuccess

I'm testing this on Android, and updating the beta app from the Play store. When I hit the purchase button I just don't see the Google Play interface to start the purchase.

**Comment by myflashlab** [comment]
Just to make sure, by ```doBilling``` you actually mean ```Billing.doPayment```, right? because we do not have a doBilling method at all.

Anyway, show us some code. we should first check and see if you are calling the methods correctly or not, for example, you need to make sure you have set the manifest correctly as described here: https://github.com/myflashlab/inAppPayments-ANE#air-xml-manifest

Another possible reason that the doPayment method may cause a problem could be that you are sending ```null``` to the resultFunction parameter of that method.

Besides that, please also send us AndroidStudio logcat stacks. You need to give us more information for us to be able to assist you. Thanks.

**Comment by myflashlab** [comment]
please let us know if you have more information to share with us?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
