### ISSUE TITLE
androidsupport.ane dependencies 

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#47]
I haven't had problems before, but recently I get a build error when exporting for Android. I added an update to com.milkmangames.extensions.GoViral ANE and thought that was causing the problem. But the ANE dev said that it's definitely caused by the androidsupport.ane.

I unchecked the androidsupport.ane in the Native Extension tab and built the app without any problems. And I tested it and the in-app purchase still works. Can you tell me if I really need the androidsupport.ane for anything related to the inapppayments.ane? 
[build-error.txt](https://github.com/myflashlab/inAppPayments-ANE/files/1185760/build-error.txt)

Attached is my build error.

**Comment by myflashlab** [comment]
We are asking users to include the AndroidSupport dependency to all our ANEs because of the infrastructure changes we are bringing to ANEs usage in mid 2018. While it might be safe to remove them from your project for now, we highly suggest you consider updating your other ANEs so you can still use the dependency. Anyhow, as a workaround, remove it for now and it still works, awesome, just remove it.
