### ISSUE TITLE
How to do a Non-Renewing Subscription?

### ISSUE THREAD

**Issue by obuw** [myflashlab/inAppPayments-ANE#52]
I'm trying to figure out how we are meant to do a Non-Renewing Subscription? Do we pick BillingType.PERMANENT or BillingType.CONSUMABLE?

Furthermore, when we read the purchase time from getPurchases, what timezone is it from? If we need to check for expiration manually, we'd need the timezone of the original purchase, and then check the date/time online (since we can't trust the device's date/time to be accurate). There is no easy way to do this with the ANE, is there?

An example would be much appreciated.

Issue #42 is a similar question but the answer is rather vague.

**Comment by obuw** [comment]
To further add to the question:

If we are meant to use BillingType.PERMANENT, then how do we "unpurchase" an item when we determine that it expired?

If we are meant to use BillingType.CONSUMABLE, then we can't use getPurchases to get information like purchaseTime at a later date, so it is not possible to restore purchases on a different device. I'm pretty sure this would not comply with apple's requirements? Is there any way to retrieve purchase info for consumables? (Disregard if we're meant to be using BillingType.PERMANENT).

**Comment by myflashlab** [comment]
About the purchaseTime, It should be in UTC I guess. ios and android documentations are here for your reference.  
https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411273-transactiondate  

https://developer.android.com/reference/com/android/billingclient/api/Purchase.html#getPurchaseTime()  

on the iOS side, you will be ok since you can create a "Non-renewing Subscriptions" in itunes. so the question is mainly concerning the Android side.

On the Android side, you can first use permanent type, and when the time arrives to expire it, you can consume the purchase using the [Billing.forceConsume](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/billing/Billing.html#forceConsume()) method.

I hope you will find this information useful.

**Comment by obuw** [comment]
Thanks. I did get it working on Android with forceConsume. But how would I do this on iOS, since I can't use forceConsume on iOS? I don't see a way to actually set the duration of a Non-renewing Subscription on iTunes Connect, so I thought we were supposed to set the duration / make it expire through the ANE?

**Comment by myflashlab** [comment]
Check out this article, It may have some useful information regarding the iOS side:
https://www.raywenderlich.com/147629/in-app-purchases-non-renewing-subscriptions-tutorial

**Comment by obuw** [comment]
Thanks, I've already read that article but was hoping this ANE would provide a better way. Ok so long story short, we have to use BillingType.CONSUMABLE on iOS and store the purchase data on iCloud or our own webserver. That is absolutely terrible.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
