### ISSUE TITLE
Purchase Permanent not working

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#62]
The code to make a consumable purchase works fine. But the permanent purchase fails to display the Google Payment screen. I get no errors or anything. Here's the code:

Billing.doPayment(
	BillingType.PERMANENT,
	'infinity_1',
	'Payload PERMANENT',
	purchaseInfinityPeecoin_result );

The only thing I can think of is that it has something to do with the 'Payload PERMANENT' string. There is no information in the docs about making Permanent purchases. All of the examples are for consumables.  

What exactly is the $payload:String? Can that be any value we wish? If not then why is it a string and not some constant? 

Is there some way to set an event listener for a failure here? 

I have not yet tested this on iOS, but hopefully will soon.

Thanks

**Comment by polyGeek** [comment]
Knock knock. Anyone home? It's been 4 days since I submitted this issue. You advertise great support help with the purchase of your ANE's. Where is it?

**Comment by myflashlab** [comment]
Well, when a consumable purchase works fine (especially on Android), it means that everything is setup correctly. Why I'm saying this with certainty? I explain in details below, hopefully this information would be helpful to you and others.

On Native Android, unlike iOS, there's no consumable type of product to begin with. inside the ANE though, to make sure the Android and the iOS sides work similar to each other, we are consuming purchases automatically inside the ANE so it feels like the product is consumable by default.

In other words: On the ANE, when you create a consumable product, the ANE will do it like a permanent one and as soon as it is completed, it will automatically consume that product. This happens in the background so the Android side would work like the iOS side.

The above procedure is exactly the same if you create a permanent product but later consume it using the ```Billing.forceConsume``` method.

Considering this fact, if you are saying that consumable purchases are working fine on Android, it means that the ANE is taking care of it completely and with success. it first purchases the permanent product then consumes it.

Now, your other product is not working for some other reasons probably outside the ANE control, maybe a simple misspelling? to make sure of that, you can open the AndroidStudio logcat and check the logs to see if it gives you more information on what could have gone wrong.

Now, about the **payload** thing, it's a simple String property which has nothing to do with your purchase. You can set its value to anything you like. This property is just there so at the time of purchasing a product, you can set its value and when the purchase finishes, this same value will be returned to you with the purchase completed data. It's just for you to help you identify your purchase easier rather than just using the product ID being returned.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
