### ISSUE TITLE
Server-side validating of Android purchase

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/inAppPayments-ANE#73]
Function onPurchaseResult called before _billing.consumeAsync finished. So if I try to validate purchase - server says me that parchase not consumed yet.

Please, make a way to listen for async consuming result.

**Comment by myflashlab** [comment]
Of course! Just create a permanent product and then when you are calling ```Billing.doPayment``` set the type to [PERMANENT](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/billing/BillingType.html)

**Comment by myflashlab** [comment]
I think it is confusing because you already have background knowledge of how the library works in native or maybe other ANEs you have used before. But If you look at this ANE from scratch, you will notice that although native side of Android and iOS work completly in different ways, we have tried to make them work almost identical for the AIR users. So an AIR user using this ANE won't be confused with differences about how the in-app-billing works on native sides.

If you have more questions, feel free to ask. Thanks.
