### ISSUE TITLE
Making auto-renewable purchases

### ISSUE THREAD

**Issue by Samuramu** [myflashlab/inAppPayments-ANE#8]
Great work with your ANE.
Is it possible to see a full documentation of doing an auto renewable purchase as well as validating / restoring one?
It's a bit confusing at this point and the only documentation I could find was for BillingType.CONSUMABLE.

Thanks!

**Comment by myflashlab** [comment]
You might think it's confusing because you may have used other ANEs and are used to do things in the hard way! :) with our ANE things are a LOT easier. let me explain how it works in simple words and you will be able to complete your task. but feel free to ask more questions if you should.

The first thing you would need to do in your app is to check the purchase history of your user and you can do that by calling ```Billing.getPurchases(``` this will return the purchase history and based on the information found in the return object, you can decide if your user can have access to your app content or not. **NOTE:** Consumable purchases will NOT be listed. only permanent and subscription payments will be listed.

Also there is method to clear local cache of the history ```Billing.clearCache();``` you might find that helpful also. *make sure to read the comments in the [sample codes](https://github.com/myflashlab/inAppPayments-ANE#air-usage)*

And finally you have the ```Billing.doPayment(BillingType.``` method to initiate a payment flow.

it's just that simple and straight forward. let me know which part you find confusing and I'll try to explain more.

**Comment by myflashlab** [comment]
will you please update us about this ticket? Do feel free to ask more questions if you have. Thanks.
